<?php
/**
 * @file
 * A block module that displays images from a list of PID's
 * in an interactive accordion rotator. Based off Accordion Rotator v1.0.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 */
function accordion_rotator_help($path, $arg) {
  if ($path == 'admin/help#accordion_rotator') {
    return '<p>' . t("Displays images including a user selected list of PID's for display on the frontpage accordion rotator") . '</p>';
  }
}
/**
 * Implements hook_menu().
 */
function accordion_rotator_menu() {
  $items = array();
  $items['accordion_rotator/setup'] = array(
    'page callback' => 'accordion_rotator_canvas_setup',
    'access arguments' => array('view accordion_rotator'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/utils.inc',
  );
  $items['admin/config/content/accordion_rotator'] = array(
    'title' => 'Accordion Rotator Configuration',
    'description' => 'Configuration for The Accordion Rotator module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('accordion_rotator_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'includes/utils.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function accordion_rotator_permission() {
  return array(
    'view accordion_rotator' => array(
      'title' => t('View Accordion Rotator Content'),
      'description' => t('Access Accordion Rotator')));
}

/**
 * Implements hook_block_info().
 */
function accordion_rotator_block_info() {
  $blocks['accordion_rotator'] = array(
    'info' => t('Accordion rotator'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function accordion_rotator_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'accordion_rotator':
      $block['subject'] = t('Block Name');
      $block['content'] = array(
        '#markup' => theme('accordion_rotator_view'),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'accordion_rotator') . '/css/main.css',
            drupal_get_path('module', 'accordion_rotator') . '/css/fonts.css',
            drupal_get_path('module', 'accordion_rotator') . '/css/accordion.css',
          ),
          'js' => array(
            drupal_get_path('module', 'accordion_rotator') . '//jquery/jquery-1.6.2.min.js',
            drupal_get_path('module', 'accordion_rotator') . '/js/resize.js',
            drupal_get_path('module', 'accordion_rotator') . '/js/script.js',
            drupal_get_path('module', 'accordion_rotator') . '/js/accordion.js',
            drupal_get_path('module', 'accordion_rotator') . '/js/pngFixer.js',
            drupal_get_path('module', 'accordion_rotator') . '/js/buttons.js',
          ),
        ),
      );
      // This settings variable is used in the js/accordion.js file to get the
      // path for the left/right buttons.//
      $my_settings = array(
        'linkpath' => url(drupal_get_path('module', 'accordion_rotator')),
      );
      drupal_add_js(array('accordion_rotator' => $my_settings), 'setting');
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function accordion_rotator_theme($existing, $type, $theme, $path) {
  return array(
    'accordion_rotator_view' => array(
      'template' => 'theme/accordion-rotator',
      'variables' => array(
        'domain_url' => url(drupal_get_path('module', 'accordion_rotator')),
        'block_data' => array(),
      ),
    ),
  );
}
